### ISSUE TITLE
No graphics on MacOS High Sierra when using .dmg release binary

### ISSUE THREAD

**Issue by rsn8887** [Enigma-Game/Enigma#10]
Using Enigma 1.21 stable release version on MacOS High Sierra, I am not seeing any graphics, only text. Here is an example screenshot:
![Image of buggy Enigma 1.21 stable graphics on MacOs High Sierra](https://s8.postimg.org/k9hd8jfz9/enigmaosx.png)

Is there a compiled version of the master branch (development version) to test?

EDIT: The homebrew version, installed with ```brew enigma install``` works! It is just the downloaded .dmg from the Enigma homepage that exhibits this bug.

**Comment by curiousdustin** [comment]
For anyone else looking to get this running on later versions of OS X, I ended up using the tip given here:
http://www.mag-heut.net/blackball/viewtopic.php?f=12&t=1305#p9632

Basically use the 1.21 release DMG, but replace one of the libraries included in the app package.

**Comment by raoulb** [comment]
If anyone here knows how to build a Mac OS package from the git master, please do so and let us know so we can publish the result. Unfortunately it seems we don't have this knowledge any more in the devel team.

**Comment by alysdexia** [comment]
Text _is_ grafic; you mean no sprites.
describing -> relating; mouse cursor -> pointer; less -> lesser; now -> no

**Comment by kencu** [comment]
FYI the binaries built by MacPorts work properly on 10.6.8 and on 10.15. I haven't tried all the systems in between.

**Comment by sidney** [comment]
I'm closing this issue as we are moving on to 1.30 and are now aware of how Homebrew got things built in 1.21. There doesn't seem much point in incorporating what they did in a 1.22 for non-Homebrew distribution.
