### ISSUE TITLE
Cannot exit game menu

### ISSUE THREAD

**Issue by legimet** [Enigma-Game/Enigma#13]
After pressing escape during a game to get to the game menu, it is impossible to get back to the game. Clicking resume, restart, or abort just causes the menu to reappear. This seems to be an issue with input grabbing, as this does not happen when using --nograb or fullscreen.

I am on Debian testing and using kwin.

**Comment by raoulb** [comment]
Hmm, I can reproduce weird behaviour, feels a bit like the `esc` key is pressed twice.
At the moment, I have no idea how to fix this.

**Comment by Legimet** [comment]
It seems that when it tries to release input, the window also moves out of focus, causing the menu to come up again.

**Comment by raoulb** [comment]
Probably fixed by #21

**Comment by schorsch3000** [comment]
i have properly the same issue in 1.20 shipped with debian buster while pressing Esc, and sometimes on level finish.
is there some kind of documentation how to build from master? `./configure` will not work without a configure file

**Comment by schorsch3000** [comment]
I did manage to build the debian version from source with this patch applied, i can confirm that it works now

**Comment by Legimet** [comment]
I can confirm that this fixes the issue for me.

**Comment by alochmann** [comment]
After the switch to SDL 2, this bug should be fixed (and replaced by other bugs). Thank you for submitting the bug report!
