### ISSUE TITLE
Occasional crash related to PulseAudio

### ISSUE THREAD

**Issue by legimet** [Enigma-Game/Enigma#23]
Occasionally Enigma crashes and I get the following error:
```
Assertion 't = find_next_time_event(m)' failed at pulse/mainloop.c:719, function calc_next_timeout(). Aborting.
Aborted
```
Probably has something to do with SDL 1.2.

**Comment by h908714124** [comment]
I get the same error. Where's the log file?

**Comment by alochmann** [comment]
This is probably fixed with our switch to SDL 2: I noticed it before in Enigma 1.21, but not anymore in 1.30-alpha. Thank you for reporting this bug.
