### ISSUE TITLE
When's 1.30?

### ISSUE THREAD

**Issue by alysdexia** [Enigma-Game/Enigma#24]

**Comment by alochmann** [comment]
An alpha version of 1.30 can be found here:
  https://github.com/Enigma-Game/Enigma/releases/tag/1.30-alpha
Please note that this is an alpha version, for bug chasing and level development. If you find a bug, don't hesitate to report it.

**Comment by sidney** [comment]
Closing this issue now that 1.30 has been released

**Comment by juanroman74454811** [comment]
merry yesterday christmas
