### ISSUE TITLE
Feature request: Item for pausing without displaying the game menu

### ISSUE THREAD

**Issue by h908714124** [Enigma-Game/Enigma#27]
Coffee cups should pause the game, but they don't, they are just dropped to the ground. There's a coffee cup for example in the level "ATARI Nostalgia", Deja vu / Oxyd pack.

**Comment by alochmann** [comment]
Enigma can be paused by using the ESC key. As far as I remember, there was no similar key in Oxyd games. Therefore, the current behaviour (noop) is an intended deviation from Oxyd games.

**Comment by h908714124** [comment]
Obviously you don't remember the original oxyd games. Sad!

**Comment by dheck** [comment]
While I agree with Andreas that the current behavior is intentional and therefore not a bug, I also think that adding a bit of "flavor" to the coffee cup would be nice. Maybe we can keep this as a feature request?

**Comment by alochmann** [comment]
Okay, I reopened this issue and renamed it. Please note that a feature request has less priority than fixing a bug, and that there are lots of other ideas and items we want to implement. Delivering a patch to us via git or via devel mailing list can speed this up.

I just confirmed that in Oxyd 1, the coffee item is consumed when using it. This leads to an incompability with at least Enigma's "Rhapsody on Cracks". Of course we could change the behaviour of it_coffee depending on the compatibility mode, but Enigma's own levels should be able to profit from such an addition, too. Therefore, if we want to introduce an item for pausing, we have to introduce a new item anyway. I suggest to name it it_tea for this exact purpose. And the idea of Enigma having tea time, while Oxyd does a coffee break, seems charming to me.

**Comment by h908714124** [comment]
I want to try but I'm a Java guy, what IDE do you folks use?

**Comment by alochmann** [comment]
Personally, I don't use an IDE at all. I use a text editor with syntax highlighting, gedit to be precise. I compile using make, and for debugging purposes, I sometimes invoke ddd.

There are project files for Xcode and Visual Studio in our repository. However, they have not been updated for 9 or 15 years, respectively. I doubt that you can still use them without massive changes. Feel free to try it.

Daniel, do you use an IDE?

**Comment by dheck** [comment]
Unfortunately, the Autotools build system we are currently using doesn't work well with modern IDEs. In the last few weeks I started to convert the existing build scripts to CMake, which eventually should make it possible to use VS/Xcode/CLion/Qt Creator and simplify development of Enigma on non-Linux OSs. 

The changes are available in the cmake branch, in case you want to try them out. I'm currently using these scripts to build Enigma on macOS using Qt Creator as the IDE.

**Comment by raoulb** [comment]
On Linux KDevelop works fine here.

**Comment by alochmann** [comment]
Done with commit 3570b1c.
