### ISSUE TITLE
Hardcoded libiconv.dylib path causes compile failure on MacOS 11 (Big Sur)

### ISSUE THREAD

**Issue by mitchblank** [Enigma-Game/Enigma#33]
I have been trying to go through some of the homebrew formulae which are having compile problems on OS/X Big Sur and came across `enigma`  I have a simple fix that seems to work here https://github.com/Homebrew/homebrew-core/pull/67960/files but I'm not sure if you will want to deal with it the same way.

The short version is that linking directly against `/usr/lib/lib*.dylib` by filename is fraught with problems because they mostly don't exist.  I say "mostly" because even though the files aren't present on the filesystem anymore there are some hacks so *some* things like calling `dlopen()` on them continues to function.

Anyway, the reference to `/usr/lib/libiconv.dylib` in `configure.ac` did seem to cause `./configure` to have problems running its test scripts, ultimately leading to it not detecting SDL properly.  For me, at least, just using the more straightforward `-liconv` fixed the problem but I'm not sure if you were using the exact pathname for some other reason (perhaps to avoid other iconvs from homebrew, etc?) 

If you must use an exact filename one Big Sur specific method is to link instead against the `.tbd` file -- this is a text file describing the library but the linker will cope with it being passed in just like passing in a `.dylib` file.  Unfortunately that means digging inside of the particular SDK you are compiling against to find a path like `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libiconv.2.tbd`

**Comment by sidney** [comment]
The only reason that the reference to `/usr/lib/libiconv.dylib` is still in the master branch is that the patches I saw in the homebrew-core formula for 1.21 did not remove it. I did put a comment to check if a number of things in `configure.ac` are still needed, and it looks like this is one of the things that can be removed. I'll do that.

**Comment by sidney** [comment]
Fixed by commit 0fc56e7ea81bec5f354785a1d5998f65d72e076a
