### ISSUE TITLE
Enigma Does Not Open in Mac Big Sur

### ISSUE THREAD

**Issue by danielpscher** [Enigma-Game/Enigma#49]
When I try to open the newest release of Enigma, I receive the message, "Enigma cannot be opened because the developer cannot be verified. MacOS cannot verify that this app is free from malware."

**Comment by sidney** [comment]
The only way to produce an app that will not result in that message the first time it is opened is for the project to have access to a paid Apple Developer subscription, which we don't. As it is, the first time you run the app, use right-click open. After that first time, double-click will work properly. This is true when the app is installed from the dmg that has been downloaded directly from the Internet.

If Homebrew is installed, the app can be installed with the following command. This issue will not happen, as a result of the "--no-quarantine" option in the command.

   `brew install --cask --no-quarantine enigma-game/enigma/enigma`
