### ISSUE TITLE
Doc: Enigma 1.30 game objects

### ISSUE THREAD

**Issue by raoulb** [Enigma-Game/Enigma#51]
Enigma 1.30 new game objects are not documented in refman.

**Comment by alochmann** [comment]
ac_marble_glass: Section 10.2.4 (within section about ac_marble)
fl_forward: Section 7.4.4
st_inkwell: Section 9.5.30
st_portal_glass: Section 9.5.50 (within section about st_portal)
st_document: New behaviour mentioned in section 9.5.19
st_pebble: Section 9.5.46

Did I miss something?
Maybe you forgot "make pdf"?

**Comment by raoulb** [comment]
You are absolutely right! My fault. Maybe I got lost searching for `ac_glass`?
