### ISSUE TITLE
ScoreManager not using rel2

### ISSUE THREAD

**Issue by double-a** [Enigma-Game/Enigma#53]
Compiler warning pointed to `rel2` not used in lev/ScoreManager.cc line 624.
Removing it would make the whole section unused thus I guess either I don't get the logic or the underlying issue is in line 627 which should use rel2 (insted of rel1), i.e.
> return (rel2 >= TRUSTED_RELEASE) ? score2 : SCORE_UNSOLVED;

**Comment by alochmann** [comment]
I am not very familiar with this part of the code. But I agree with your assessment, this should probably be rel2 instead of rel1.

Please keep this issue open, I will fix this later, when 1.31 approachs.

**Comment by alochmann** [comment]
I took a dive into Ronald's code, and yes, you were right, that was a typo. Thanks!
